### ISSUE TITLE
Value detection

### ISSUE THREAD

**Issue by SeenaLibin** [FerreroJeremy/ln2sql#1]
All the values in NLP is detected as OOV in sql query. Is there any technique to identify the values in SQL generation

**Comment by FerreroJeremy** [comment]
Hi!
Thx U for our interest. I am aware of the issue, wich is mentioned several time in the README and the source.
Unfortunately, I had to give up the development of the project. But yeah, I have several lines of inquiry:
- You can parse the _.sql_ dump file to identify all the possible values for a column, for instance.
- You can create rules of regular grammar to identify the values in the NLP input sentence. But this technique is more complex to implement and especially break the flexibility of interpretation of ln2sql.

I hope I have helped you. Don't hesitate if you have additional questions.

**Comment by jamsheer-thottathil** [comment]
Any chance to update repo with the same and It will be  great appreciable  .

**Comment by FerreroJeremy** [comment]
Unfortunately, not at the moment, no. First, I'd like to finish my Ph.D. 
Or maybe this summer,  when I'm not in rush period.

**Comment by jamsheer-thottathil** [comment]
ok ,thank you

**Comment by FerreroJeremy** [comment]
@maverickjoy is apparently working on this issue but his [fork](https://github.com/maverickjoy/ln2sql) doesn't work yet (at least for me). Maybe you can get in touch with him ;)

**Comment by rupinder1133** [comment]
@FerreroJeremy  [ln2sqlmodule](https://github.com/rupinder1133/ln2sqlmodule) can detect values but has some limitations, will detect values but requires some assignment operator between column name and value(which i think should be good for most of the cases). the assignment operators can be one of `[" equals to "," equal to ","="," is ",":"," equals "," equal "," than "]`, see line 636 in Parser.py
ps. this contribution is by @maverickjoy

**Comment by FerreroJeremy** [comment]
@rupinder1133 @maverickjoy You really should learn to do pull requests guys :joy:

**Comment by FerreroJeremy** [comment]
Don't worry. I was kidding ;)
thx for the help!

**Comment by rupinder1133** [comment]
I do 😂 had to make [ln2sqlmodule](https://github.com/rupinder1133/ln2sqlmodule) for my requirements, din't find time to request a pull, will try in future

**Comment by FerreroJeremy** [comment]
A lot of improvements remains to be done in this way.

For instance, with the entry:
`python ln2sql.py -d database/city.sql -l lang/english.csv -j test.json -i "count how many city there are where the name is greater than Matthew ?"`

the result is:
```
SELECT COUNT(*)
FROM city
INNER JOIN emp
ON emp.cityId = city.id
WHERE emp.name > 'greater';
```

I assume that this sentence is stupid but it's just an example :laughing:
Also, I find that this implementation (request #7) of the values extraction/detection breaks the laxity of the rules identification (during parsing) :cry:
Unfortunately, I do not have time to improve that - maybe after my PhD (so in the first quarter of 2018).

**Comment by rupinder1133** [comment]
That happens because 'name' column is in emp table and there is no column by that name in city table (it's cityName in city table). Can you elaborate what's wrong with it ?

**Comment by maverickjoy** [comment]
Hi, I was unable to look into this for a while(was slightly busy). But I have managed to take out some time, I have improved the value extraction logic, removed some loose cases and bugs too. I have also implemented all new LIKE feature query in it. Now it is able to do value extraction in much better way plus your query which you mentioned above is also now working :P 
RESULTS :
![23468291_1972396096335944_979469449_o](https://user-images.githubusercontent.com/11170508/32622646-8fdba35c-c5a9-11e7-86cf-c56f119635c2.jpg)
![23482917_1972395883002632_2091975623_o](https://user-images.githubusercontent.com/11170508/32622648-90785472-c5a9-11e7-9742-8277cda97257.jpg)
![23484429_1972395873002633_379445009_o](https://user-images.githubusercontent.com/11170508/32622649-90b21f86-c5a9-11e7-97b5-7f72732dcf9b.jpg)


I'll be creating a pull request as @FerreroJeremy  , you had mentioned hope you like my part of the contribution. I feel ln2sql is great, and works for general use-cases

**Comment by maverickjoy** [comment]
Hi, I was unable to look into this for a while(was slightly busy). But I have managed to take out some time and have improved the value extraction logic, removed some loose cases and bugs too. I have also implemented all new 'LIKE' feature query in it. Now it is able to do value extraction in much better way plus your query which you mentioned above is also now working :P

PRESENT RESULTS :
![23468291_1972396096335944_979469449_o](https://user-images.githubusercontent.com/11170508/32624509-80e01846-c5af-11e7-9d1b-eb8d4bba85e5.jpg)
![23484429_1972395873002633_379445009_o](https://user-images.githubusercontent.com/11170508/32624511-814eb3f0-c5af-11e7-8499-4a8212f7bb33.jpg)
![screenshot from 2017-11-10 00-20-12](https://user-images.githubusercontent.com/11170508/32624512-817edf1c-c5af-11e7-9771-ae14edcca5cf.jpg)
![screenshot from 2017-11-10 00-35-55](https://user-images.githubusercontent.com/11170508/32624513-81ac67c0-c5af-11e7-9c48-efae40ac4174.jpg)

I'll be creating a pull request as @FerreroJeremy , you had mentioned. Hope you like my part of the contribution. I feel ln2sql is Great, and works for most of the general use-cases.

**Comment by FerreroJeremy** [comment]
Yeah! You rock!
Your contributions are sincerely appreciated and significant!
Thank you again.

**Comment by maverickjoy** [comment]
Hi , I did look into it, value 'rupinder' was being extracted, but the problem was something else, and then finally found out that this bug is not introduced by me  :sweat_smile: , guilty consciously I did revert back all my changes to a previous commit and saw that its still there. So I guess its a prevailing bug :P , Understand its serious and needs to be removed but as far as I can see as its a join query, Present our project is only able to do INNER JOIN emp , maybe because foreign key is in it, but cannot do join on city. Maybe my underastanding is wrong. But its something around this and needs to be looked upon.

**Comment by FerreroJeremy** [comment]
@maverickjoy yeah, sorry for the unjustified accusation 😅 I just fixed the problem.
But, I found a new one (sorry 😂 ).

When the input is `python ln2sql.py -d database/city.sql -l lang/english.csv -j output.json -i "Show data for city where cityName is 'Pune Agra'"`, the output is : 
```
SELECT *
FROM city
WHERE city.cityName = ''pune';
```
instead of :
```
SELECT * 
FROM city 
WHERE city.cityName = 'Pune Agra';
```

**Comment by maverickjoy** [comment]
Yup, It's fixed and again a prevailing bug  :joy:
