### ISSUE TITLE
The school.sql is not in the database

### ISSUE THREAD

**Issue by WoNiuHu** [FerreroJeremy/ln2sql#2]
could you please put the school.sql in datasetbase ?

**Comment by FerreroJeremy** [comment]
There is no _school.sql_ database file. It was just an example for the readme file.
The closest thing is the _tal.sql_ file, but it is in French, so _student_ = _eleve_, _classroom_ = _classe_, _professor_ = _professeur_, and so on.
The best way to try ln2sql is to try on one of your sql dump files. If you have any issues to do that, I could help you.

**Comment by FerreroJeremy** [comment]
@WoNiuHu, I have just added a school.sql file in the _database_\ repository ;)
