### ISSUE TITLE
Convert to a package to make it pip installable

### ISSUE THREAD

**Issue by shashank88** [FerreroJeremy/ln2sql#23]
Currently the only way to run is to clone and execute. Will convert to a python package
https://python-packaging.readthedocs.io/en/latest/

**Comment by shashank88** [comment]
Done. pip install ln2sql works!

**Comment by anupam20sep** [comment]
Please check it again. I did pip install ln2sql it works fine but it only creates a .info dir in site-packages and no package dir.  I checked the tar on pypi and it seems there are no packages inside other setup.py and other stuffs... size is 4.6 kB
