### ISSUE TITLE
JOIN statements

### ISSUE THREAD

**Issue by rupinder1133** [FerreroJeremy/ln2sql#3]
As mentioned in the documentation joins are supported but I can't seem to generate a SQL with JOIN. I have tried with a sql dump with 2 tables with proper foreign key and primary keys.

SQL dump : [tables.sql.zip](https://github.com/FerreroJeremy/ln2sql/files/1406720/tables.sql.zip)

Please provide an example natural language query for JOINs

**Comment by FerreroJeremy** [comment]
Hey, thank you for reporting the bug.
I've just been taking a look and I seeing where it came from (I adding an issue).
Unfortunately, I really do not have time to correct it.
Maybe I will finish this project after my PhD (so in the first quarter of 2018).

**Comment by rupinder1133** [comment]
After some exploration here are the findings (might help someone else):
- 'PRIMARY KEY' statement should be in the CREATE TABLE itself not in ALTER TABLE i.e. if you have set the primary key after creating the table, ln2sql won't detect it
- For JOIN it works on the intersection of list of primary keys of the tables, so column names must be same for ON table_1.col = table_2.col, which will not always be true
- column name must no exists in the table name mentioned in the query for ln2sql to create a JOIN SQL query

Will try to fix if i can

**Comment by FerreroJeremy** [comment]
Duplicate with issue #5
