### ISSUE TITLE
No table name found in sentence

### ISSUE THREAD

**Issue by dhmodi** [FerreroJeremy/ln2sql#38]
Hi Team,

While running sample, "What is the average age of students whose name is Doe or age over 25?" it gives error "No table name found in sentence".

python -m ln2sql.main -d database_store/school.sql -l lang_store/english.csv -j output.json -i "What is the average age of students whose name is Doe or age over 25?"

It seems keyword "students" is not matching in database "school.sql".

Regards,
Dhaval

**Comment by FerreroJeremy** [comment]
Please read the readme ^^

> Beware that ln2sql cannot therefore automatically solve the gender and number problem. So if the word "students" is in the input sentence, it does not match with the table "student" in the model of data. To do that, the equivalence "students → student" must be appear in the used thesaurus.

If you want a version using a tagger to directly lemmatize/stemming a word, feel free to implement it ;)
