### ISSUE TITLE
Parser not defined error

### ISSUE THREAD

**Issue by pritnal1** [FerreroJeremy/ln2sql#42]
Hi Need one help 👍
I am getting parser not defined after submitting the GUI form . PFA 
![parser_not_defined_error](https://user-images.githubusercontent.com/23476395/36195570-efa390ac-1193-11e8-9325-4a66939d393b.PNG)

**Comment by FerreroJeremy** [comment]
The pypi version is really not updated; it does not include most of features of the github version (see @shashank88 for more info).
Sorry for the inconvenience.
