### ISSUE TITLE
Query churned out seems to be wrong for the example in README.md

### ISSUE THREAD

**Issue by nikhil-phadtare** [FerreroJeremy/ln2sql#44]
The out put should be a simple query which should not be using a join. The example uses the city data model. Please help me out with this.

**Command:**
```bash 
python3 -m ln2sql.main -d database_store/city.sql -l lang_store/english.csv -j output.json -i "Count how many city there are with the name blob?"
```
**Generated sql:**
```sql
SELECT COUNT(*)
FROM city
INNER JOIN emp
ON city.id = emp.cityId
WHERE emp.name = 'with';
```

**Comment by FerreroJeremy** [comment]
The column _name_ is only present in the table _emp_ (in the table _city_, the column is called _cityName_), so without the use of the thesaurus feature, this output is correct.
