### ISSUE TITLE
Join between tables

### ISSUE THREAD

**Issue by Vishnubala95** [FerreroJeremy/ln2sql#45]
Hi everyone,
I am facing difficulty in forming a question based on joins. How to write a question to access multiple tables using joins?Is there any chance?

Can you please provide an example with school.sql file available in the database_store

**Comment by FerreroJeremy** [comment]
Hi,

I have no simple example with school database, but you can find many examples with the other databases in the [tests file](https://github.com/FerreroJeremy/ln2sql/blob/master/tests/test_unit.py).
