### ISSUE TITLE
Question about accuracy/efficiency

### ISSUE THREAD

**Issue by Mytrill** [FerreroJeremy/ln2sql#51]
Hi,

I have read the paper and checked out the library, and I am considering using a similar method to the one used here to enable users to query a database with a natural language.

I saw in the other issue that you are no longer continuing this project, could you tell me what is the reason?
Is it due to performance or accuracy reason?
Or maybe you have find some specific limitations that make this "non machine learning" approach not useable in real life?

One of the limitation I could see would be that some words that are not a noun actually dictate the table/colmun values should be selected from (for example, "who takes the biology class?" -> "SELECT * FROM student WHERE ...").

Based on your experience with this approach, would you advice for or against using a similar technique in production?

Thank you in advance for the reply!

**Comment by FerreroJeremy** [comment]
Hi, thank you for your interest in this project.

No, the reason is non technical, it's simpler. This project was just a little student project, at the beginning. But then, I started a Ph.D, and now a new work so I don't have time for this project.

Sorry.
