### ISSUE TITLE
Join on pk and fk columns with different name unsupported 

### ISSUE THREAD

**Issue by FerreroJeremy** [FerreroJeremy/ln2sql#6]
Exemple of correct declarations of pk and fk but unsupported by ln2sql :

```
ALTER TABLE `city`
  ADD PRIMARY KEY (`id`),
  ADD KEY `id` (`id`);

ALTER TABLE `emp`
  ADD CONSTRAINT `emp_ibfk_1` FOREIGN KEY (`cityId`) REFERENCES `city` (`id`);
```

**Comment by rupinder1133** [comment]
I have created a module for ln2sql which not supports parsing of primary key and foreign key from CREATE table as well as ALTER table statements, also inner join is applied on foreign key.
check it out here : https://github.com/rupinder1133/ln2sqlmodule

**Comment by FerreroJeremy** [comment]
Oh! Thank you! I'll incorporate that after my break ;)

If you want to contribute, don't hesitate to use pull request (for the variable identification in the where for instance!

**Comment by FerreroJeremy** [comment]
@rupinder1133 I just commited your contribution my way because of my contribution of this morning.
Thank you again ;)

**Comment by rupinder1133** [comment]
I'll try my best to amend the changes and request a pull in ln2sql
